# Improve colors
#set -g default-terminal 'screen-256color'
set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",*256col*:Tc"

# Send xterm compatible control arrow keys so they work with Vim.
setw -g xterm-keys on

# Set scrollback buffer to 200000
set -g history-limit 200000

# Customize the status line
set -g status-fg  green
set -g status-bg  black 
#display session name instead of ID
set-option -g status-justify centre
set -g status-left "[#S]"

#prefix Key
set -g prefix ^x
unbind %
unbind C-b
unbind '"'

bind | split-window -h
bind - split-window -v
bind N break-pane

# Reload the tmux config.
bind r source-file ~/.tmux.conf

# Highlight active window

# Set window notifications
setw -g monitor-activity on
set -g visual-activity on

# Automatically set window title
setw -g automatic-rename on

# Start windows and panes index at 1, not 0.
set -g base-index 1
setw -g pane-base-index 1

set-window-option -g window-status-style fg=colour39
set-window-option -g window-status-current-style fg=colour244
set-window-option -g window-status-current-style bg=colour235

#command history file
set -g history-file /home/ice/.tmux_history

#sensible
# Increase tmux messages display duration from 750ms to 4s
set -g display-time 1000

#enable bash history in tmux, run bash on tmux startup
#set-option -g default-command bash
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
